name: Build and Release sing-box rule-set

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install sing-box
        run: |
          sudo bash -c "$(curl -fsSL https://sing-box.sagernet.org/install.sh)"
        # Скрипт установки sing-box с официального сайта:
        # он скачивает и ставит бинарник sing-box для Linux с GitHub Releases [web:89].

      - name: Check sing-box version
        run: |
          sing-box version

      - name: Compile rule-set
        run: |
          sing-box rule-set compile --output kino-pub.srs kino-pub.json

      - name: Create GitHub Release and upload srs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG="${GITHUB_REF#refs/tags/}"

          # Создаём или обновляем релиз для этого тега
          gh release create "$TAG" kino-pub.srs \
            --title "$TAG" \
            --notes "Binary sing-box rule-set for kino.pub" \
            --repo "$GITHUB_REPOSITORY" \
            --generate-notes || \
          gh release upload "$TAG" kino-pub.srs \
            --repo "$GITHUB_REP
